2021-01-07 19:59:50,588    run.py   INFO  run disconnect all stored in config
2021-01-07 19:59:50,593    run.py   INFO  Disconnecting subsysNQN
Failed to open /sys/class/nvme/nvme0/device/subsystem_vendor with errno No such file or directory
Failed to open /sys/class/nvme/nvme0/device/subsystem_device with errno No such file or directory
Failed to open /sys/class/nvme/nvme0/device/vendor with errno No such file or directory
Failed to open /sys/class/nvme/nvme0/device/device with errno No such file or directory
Failed to open /sys/class/nvme/nvme0/device/class with errno No such file or directory
2021-01-07 19:59:51,162    run.py   INFO  nvme connect -t rdma -a 10.10.0.2 -n subsysNQN -s 4420 -q 00000000-0000-0000-0000-ac1f6b5868a8 -i 8
Failed to open /sys/class/nvme/nvme0/device/subsystem_vendor with errno No such file or directory
Failed to open /sys/class/nvme/nvme0/device/subsystem_device with errno No such file or directory
Failed to open /sys/class/nvme/nvme0/device/vendor with errno No such file or directory
Failed to open /sys/class/nvme/nvme0/device/device with errno No such file or directory
Failed to open /sys/class/nvme/nvme0/device/class with errno No such file or directory
